### ISSUE TITLE
Issue with matching context file name with entity name following same pattern

### ISSUE THREAD

**Issue by terazus** [datatagsuite/context#3]
{
  "@context": {
    "sdo": "https://schema.org/",
    "Identifier": "sdo:Thing",
    "identifier": "sdo:identifier",
    "identifierSource": {
       "@id": "sdo:Property",
       "@type": "sdo:Text"
    }
  }
}
=> "Identifier" key should be "Identifier_info" or "IdentifierInfo" or both context or schema files should be renamed identifier_sdo_schema.json and identifier_schema.json

**Comment by agbeltran** [comment]
Thanks, I see that we didn't exactly follow the same rule as in the other schemas, but as there are dependencies on this, we might need to keep a dictionary with these mappings for the other project, rather than changing the context files. I need to analyse better the impact of this potential change.

**Comment by terazus** [comment]
Others tracked issues:
alternate_identifier_sdo_context.json: no base attribute (should be AlternateIdentifier)
date_info_sdo_context.json: base attribute should be DateInfo, not Date
molecular_entity_sdo_context.json: base attribute should be MolecularEntity, not BiologicalEntity
taxonomic_info_sdo_context.jsonld: base attribute should be TaxonomicInfo not TaxonomicInformation
